---
# This playbook deploys the whole application stack in this site. 

- name: Install and configure mariadb, gunicorn, and nginx. Deploy the flask app.
  hosts: webserver
  roles:
    - mariadb
    - gunicorn
    - nginx