---
- name: Install nginx
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - nginx
    - ssl-cert

- block:
    - name: Create a directory for custom nginx configuration
      ansible.builtin.file:
        path: /etc/nginx/custom
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Set nginx.conf
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf

    - name: Set default.conf
      ansible.builtin.template:
        src: default
        dest: /etc/nginx/sites-available/default

    - name: Set nginx-general.conf
      ansible.builtin.template:
        src: nginx-general.conf.j2
        dest: /etc/nginx/custom/general.conf

    - name: Set nginx-security.conf
      ansible.builtin.template:
        src: nginx-security.conf.j2
        dest: /etc/nginx/custom/security.conf

    - name: Set nginx-ssl.conf
      ansible.builtin.template:
        src: nginx-ssl.conf.j2
        dest: /etc/nginx/custom/ssl.conf

    # - name: Set letsencrypt.conf
    #   ansible.builtin.template:
    #     src: nginx-letsencrypt.conf.j2
    #     dest: /etc/nginx/custom/letsencrypt.conf

    - name: Set nginx-site.conf
      ansible.builtin.template:
        src: nginx-site.conf.j2
        dest: /etc/nginx/sites-available/{{ site_domain_name }}

    - name: Enable site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/{{ site_domain_name }}
        dest: /etc/nginx/sites-enabled/{{ site_domain_name }}
        state: link

    - name: Generate ssl certificate
      ansible.builtin.script: 
        # cmd: generate-ssl-cert.sh --domain_name "{{ domain_name }}"  --subdomain_name "{{ subdomain_name }}" --email "{{ email }}"
        cmd: generate-ssl-cert.sh
      args:
        creates: /etc/letsencrypt/live/{{ site_domain_name }}/fullchain.pem
      # when: "{{ inventory_name }} is 'production-inventory.yml'"
      # when: "'production-inventory.yml' in inventory_file"
  
  notify: restart nginx
  tags: nginx_conf
