---
- name: Install MariaDB
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - mariadb-server
    - mariadb-client
    - python3-pymysql

- name: Set mariadb root password
  community.mysql.mysql_user:
    name: root
    password: "{{ db_root_password }}"
    host_all: true
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  failed_when: false

- name: Remove anonymous users
  community.mysql.mysql_user:
    name: ""
    host_all: true
    state: absent
    login_user: root
    login_password: "{{ db_root_password }}"

- name: Create database for application
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ db_root_password }}"

- name: Create database user with all database privileges
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    login_user: root
    login_password: "{{ db_root_password }}"
