---
- name: Install MariaDB
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: 
    - mariadb-server
    - mariadb-client
    - python3-pymysql

- name: Set mariadb root password
  community.mysql.mysql_user:
    name: root
    password: "{{ db_root_password }}"
    host_all: yes
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Remove anonymous users
  community.mysql.mysql_user:
    name: ""
    host_all: yes
    state: absent
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create database for application
  community.mysql.mysql_db:
    name: "{{ db }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create database user with all database privileges
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock



