---
- name: Deploy Flask App
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    repo_url: 'https://github.com/hdaojin/itnsa.git'
  tasks:
    - name: Install python3, python3-pip, python3-venv
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip
        - python3-venv

    - name: Create the project directory
      ansible.builtin.file:
        path: /srv/itnsa
        state: directory
        mode: '0755'

    - name: Pull the latest code of the application
      ansible.builtin.git:
        repo: "{{ repo_url }}"
        dest: /srv/itnsa

    - name: Create a virtualenv for the project
      ansible.builtin.command:
        cmd: /usr/bin/python3 -m venv /srv/itnsa/.venv
        creates: /srv/itnsa/.venv

    - name: Install pip requirements
      ansible.builtin.pip:
        requirements: /srv/itnsa/requirements.txt
        executable: /srv/itnsa/.venv/bin/pip

    - name: Create a systemd service file
      ansible.builtin.template:
        src: templates/itnsa.service.j2
        dest: /etc/systemd/system/itnsa.service

    - name: Start and enable the systemd service
      ansible.builtin.systemd:
        name: itnsa
        state: started
        enabled: yes


    
