---
# Create normal user, but no sudo,  no python installed, no ssh key
# usage: ansible-playbook -i inventory.yml ansible-initialization.yml -k -K
- name: Initialization of the system for Ansible usage
  hosts: all
  become: True
  become_method: su
  become_user: root
  gather_facts: False
  vars:
    - ssh_public_key: ~/.ssh/id_rsa.pub
  tasks:
    - name: Install python
      ansible.builtin.raw: apt install -y python3 sudo python3-apt apt-transport-https ca-certificates
      register: apt_output
      changed_when: "'will be installed' in apt_output.stdout"
      # changed_when: False

    - name: Add ssh public key 
      ansible.posix.authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ lookup('ansible.builtin.file', '{{ ssh_public_key }}' ) }}"
      
    - name: Configure sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        # line: "{{ ansible_user }} ALL=(ALL:ALL) NOPASSWD: ALL"
        line: "{{ ansible_user }} ALL=(ALL:ALL) ALL"
        validate: /usr/sbin/visudo -csf %s
        state: present
  
