---
- name: System Initialization for debian
  hosts: all
  become: True
  vars:
    packages:
      - python3-apt 
      - apt-transport-https 
      - ca-certificates
      - systemd-timesyncd
      - vim          
      - bash-completion
      - git
      - curl
      - wget
      - iptables
      - iptables-persistent 

  tasks:
    # Be aware that inconsistencies between the hostname and hosts can cause Ansible SSH connection timeouts.
    - name: Set hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        search_string: "127.0.1.1"
        line: "127.0.1.1 {{ hostname }} debian"
        state: present
      tags: hosts

    - name: Set Hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"
        use: debian
      when: "'production-inventory.yml' in inventory_file"

    - name: Set timezone
      community.general.timezone:
        name: "{{ timezone }}"

    - name: set apt source
      ansible.builtin.copy:
        src: files/apt.sources.list
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: 0644
        backup: yes
      when: "'production-inventory.yml' not in inventory_file"

    - name: Upgrade System
      ansible.builtin.apt:
        upgrade: full
        update_cache: true
      ignore_errors: yes
      notify: reboot
      # when: "'production-inventory.yml' in inventory_file"

    - name: Install commonly used software
      ansible.builtin.apt:
        update_cache: False
        pkg: "{{ packages }}"

    - name: Clean no longer required packages
      ansible.builtin.apt:
        autoremove: yes
        autoclean: yes

    - name: ensure dbus is running
      ansible.builtin.systemd:
        name: dbus
        state: started
        enabled: true

    - block:
      - name: Set ntp server
        ansible.builtin.lineinfile:
          path: /etc/systemd/timesyncd.conf
          regexp: '^#?NTP'
          line: "NTP={{ ntp_servers[0] }}"
          state: present
          # backup: yes

      - name: Set ntp backup server
        ansible.builtin.lineinfile:
          path: /etc/systemd/timesyncd.conf
          regexp: '^#?FallbackNTP'
          line: "FallbackNTP= {{ ntp_servers[1:] | join(' ') }}"
          state: present
      notify:
        - restart systemd-timesyncd

    - block:
      - name: Ensure localisation files are available
        community.general.locale_gen:
          name: "{{ item }}"
          state: present
        with_items:
          - "{{ locale }}"
          - "{{ language }}"

      - name: Configure locale
        ansible.builtin.command:
          # cmd: update-locale LANG={{ locale }} LANGUAGE={{ language }}
          cmd: localectl set-locale LANG={{ locale }} LANGUAGE={{ language }}

    - name: Configure sshd safe settings
      ansible.builtin.template:
        src: templates/safe-sshd.conf.j2
        dst: /etc/ssh/sshd_config.d/safe-sshd.conf
        owner: root
        group: root
        mode: 0644
      notify: restart sshd

    - name: loading iptables rules 
      # ansible.builtin.script: files/iptables-webserver.sh -p "{{ ssh_port }}"
      ansible.builtin.template:
        src: templates/rules.v4.j2
        dest: /etc/iptables/rules.v4
      notify: "reload iptables"

  handlers:
    - name: restart sshd
      ansible.builtin.systemd:
        name: sshd
        state: restarted
        enabled: true

    - name: restart systemd-timesyncd
      ansible.builtin.systemd:
        name: systemd-timesyncd
        state: restarted
        enabled: true

    - name: reload iptables
      ansible.builtin.systemd:
        name: netfilter-persistent
        state: restarted
        enabled: true
    
    - name: reboot
      ansible.builtin.reboot:
        reboot_command: reboot

      



