---
- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: restart gunicorn
  ansible.builtin.systemd:
    name: "{{ app_module_import }}"
    state: restarted
    enabled: yes