---
- name: Daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart gunicorn
  ansible.builtin.systemd:
    name: "{{ app_module_import }}"
    state: restarted
    enabled: true
